name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release Please Action
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          release-type: simple
 
